name: Terraform Deployment

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1

      - name: Check S3 bucket access
        run: |
          if aws s3api head-bucket --bucket my-raw-data-bucket --region eu-west-1 2>/dev/null; then
            echo "✅ Bucket exists and is accessible"
          else
            echo "❌ Bucket does not exist or access denied"
            exit 1
          fi

      - name: Terraform Init
        run: terraform -chdir=terraform init

      - name: Terraform Plan
        id: plan
        run: |
          terraform -chdir=terraform plan -out=tfplan
          # Check if there are any changes
          if grep -q "No changes. Infrastructure is up-to-date." <<< "$(terraform show -no-color tfplan)"; then
            echo "no_changes=true" >> $GITHUB_ENV
          else
            echo "no_changes=false" >> $GITHUB_ENV
          fi

      - name: Terraform Apply
        if: env.no_changes == 'false' && github.ref == 'refs/heads/main'
        run: terraform -chdir=terraform apply -auto-approve tfplan
